config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks", registrations: 'registrations' }
  root 'places#index'

  resources :entries do
    resources :comments
  end
  resources :users
  resources :places do
    resources :posts
  end

  get '/users/:id/follow_user', to: 'relationships#follow_user', as: :follow_user
  get '/users/:id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get '/users/:id/following', to: 'users#following', as: :following
  get '/users/:id/followers', to: 'users#followers', as: :followers
  get '/users/:id/journal', to: 'users#journal', as: :journal
  get '/search', to: 'search#search', as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :entries, dependent: :destroy
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'FollowRelationship'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'FollowRelationship'
  has_many :following, through: :following_relationships, source: :following

  has_many :comments, dependent: :destroy

  has_many :places
  has_many :posts, :through => :places

  has_attached_file :profile_picture,
                    :default_url => ':style/default.png',
                    :styles => { :small => "45x45#", :thumb => "80x80#", :medium => "140x140#"}


  validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\z/


  # Follows a user by setting the following_id to the given user
  # and the follower_id to the id of this User object
  def follow(user_id)  
    following_relationships.create(following_id: user_id, follower_id: self.id)
  end

  # Unfollows a user by destroying the relationship
  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  # Determines whether or not the given user is being followed by
  # this User object. Returns true or false
  def following?(user_id)
    user = User.find_by(id: user_id)
    self.following.include?(user) ? true : false
  end

  # Determines whether or not the given user is a follower of
  # this User object. Returns true or false
  def followers?(user_id)
    user = User.find_by(id: user_id)
    self.followers.include?(user) ? true : false
  end

  # Returns a users full name by adding the first and last names
  def full_name
    full_name = self.first_name + " " + self.last_name
  end

  # Finds user where search term matches first_name, last_name, or email
  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
  end

  # Gets information from facebook
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end      
  end
end

app/controllers/User/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user 
  end
end

app/controllers/User/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :following, :followers, :journal, :places]

  # Displays all users
  def index
    @users = User.all
  end
  
  # Displays a user's profile page
  def show
    @places = @user.places.order("created_at asc")
  end

  # displays a page of users that the given user is following
  def following
    @following = @user.following
  end

  # displays a page of users that are following a given user
  def followers
    @followers = @user.followers
  end

  # returns all of a user's journal entries
  def journal
    @entries = @user.entries.order("created_at desc")
  end

  private

  # Finds the specific user from the id sent through params
  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_profile_heading.html.erb
<!-- Display the user's name, followers, and profile picture -->
<div class="profile-heading">
  <div class="info">
    <h2><%= user.full_name %></h2>
    <p><%= link_to display_following(user.id), following_path(user) %> <%= link_to display_followers(user.id), followers_path(user) %></p><br>
  </div>
  <%= image_tag user.profile_picture.url(:medium), class: 'profile-img img-circle' %>

  <div class="profile-links">

    <%= link_to "Places", user_path(user), class: "btn btn-default" %>
    <%= link_to "Journal", journal_path, class: 'btn btn-default' %>

      <!-- Only give the current user options to edit data if they
        are logged in. They can view most information without being
        logged in, but obviously can't follow, unfollow, create new
        entries, or edit profile. -->
    <% if current_user %>

      <!-- If the profile page shown is the current user's page,
          they have the option of creating a new journal entry
          or editing their own profile. -->
      <% if @user == current_user %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-default" %>

        <!-- Otherwise, they are given options to follow or unfollow
            the user. -->
      <% else %>

        <!-- Display either follow or unfollow buttons depending on
            whether or not the current user is already following the
            displayed user -->
        <% if current_user.following?(user.id) %>
            <%= link_to "Unfollow", unfollow_user_path, class: "btn btn-default" %><br>
        <% else %>
            <%= link_to "Follow", follow_user_path, class: "btn btn-default" %><br>
        <% end %> <!-- ends if current_user.following?(@user.id) -->
      <% end %> <!-- ends if @user = current_user -->
    <% end %> <!-- ends if current_user -->
  </div>
</div>

app/views/users/_user.html.erb
<% if array.length > 0 %>
  <div class="row">
    <% array.each do |user| %>
      <div class="col-md-4">
        <div class="profile-card">
          <%= image_tag user.profile_picture.url(:thumb), class: 'img-circle pic-thumbnail' %>
          <%= link_to user.full_name, user_path(user), class: 'name-thumbnail' %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="message"><%= message %></p>
<% end %>

app/views/users/followers.html.erb
<%= render partial: 'profile_heading', locals: {user: @user} %>

<%= render partial: 'user', locals: {array: @followers, message: "#{@user.first_name} has no followers yet."} %>

app/views/users/following.html.erb
<%= render partial: 'profile_heading', locals: {user: @user} %>

<%= render partial: 'user', locals: {array: @following, message: "#{@user.first_name} is not following anyone yet."} %>

app/views/users/index.html.erb
<%= render partial: 'user', locals: {array: @users, message: "No matches were found."} %>

app/views/users/journal.html.erb
<%= render partial: 'profile_heading', locals: {user: @user} %>

<h2 class="heading">Journal</h2>

<div class="heading">
  <% if @user == current_user %>
    <%= link_to "New Journal Entry", new_entry_path, class: 'btn btn-default' %>
  <% end %>
</div>

  <% if @user.entries.length > 0 %>
    <!-- Renders the entry partial to display the list of
        the current user's journal entries. -->
    <% @user.entries.each do |entry| %>
      <%= render partial: 'entries/entry', locals: {entry: entry} %>
    <% end %>
  <% else %>
    <p class="message">There are no entries yet.
  <% end %>
</div>

app/views/users/show.html.erb
<%= render partial: 'profile_heading', locals: {user: @user} %>

<h2 class="heading">Places</h2>

<div class="row">
  <% if current_user == @user %>
    <div class="col-sm-3">
      <div class="places">
        <a class="name-thumbnail place-name glyphicon glyphicon-plus add-new-place" id="new-place" href="<%= new_place_path %>"></a>
      </div>
    </div>
  <% end %>

  <% if @places.length > 0 %>
    <% @places.each do |place| %>
      <div class="col-sm-3">
        <div class="places">
          <%= link_to place.name, place_path(place), class: 'name-thumbnail place-name' %>
        </div>
      </div>
    <% end %>

  <% else %>
    <% unless @user == current_user %>
      <p class="message"><%= @user.first_name %> hasn't created any places yet.</p>
    <% end %>
  <% end %>
</div>