config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks", registrations: 'registrations' }
  root 'places#index'

  resources :entries do
    resources :comments
  end
  resources :users
  resources :places do
    resources :posts
  end

  get '/users/:id/follow_user', to: 'relationships#follow_user', as: :follow_user
  get '/users/:id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get '/users/:id/following', to: 'users#following', as: :following
  get '/users/:id/followers', to: 'users#followers', as: :followers
  get '/users/:id/journal', to: 'users#journal', as: :journal
  get '/search', to: 'search#search', as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :place

  has_attached_file :post_photo, default_url: ':style/no-image.png', styles: { medium: "236x300#" }
  validates_attachment_content_type :post_photo, content_type: /\Aimage\/.*\z/

  # Returns the user who owns the place and therefore the post
  def post_user
    place = self.place
    place.user
  end

  # Finds post where search term matches description or link
  def self.search(search)
  where("description ILIKE ? OR link ILIKE ?", "%#{search}%", "%#{search}%") 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_place
  before_action :owned_post, only: [:edit, :update, :destroy]  

  # list all posts
  def index
    @posts = @place.posts.order("created_at desc")
  end

  # show a specific post
  def show
  end

  # renders form to create new post
  def new
    @post = Post.new
  end

  # creates a new post
  def create
    @post = Post.new(place_id: @place.id)
    @post.update(post_params)
    if @post.save
      redirect_to place_post_path(@place, @post)
    else
      redirect_to controller: 'posts', action: 'new'
    end
  end

  # renders form to edit post
  def edit
  end

  # updates post
  def update
    if @post.update(post_params)
      redirect_to place_post_path(@place, @post)
    else
      redirect_to controller: 'posts', action: 'edit'
    end
  end

  # deletes a post
  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_place
    @place = Place.find(params[:place_id])
  end

  def post_params
    params.require(:post).permit(:link, :description, :post_photo)
  end

  def owned_post  
    unless current_user == @post.post_user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<!-- Form components for creating new posts and editing posts. Form styled with bootstrap. -->
<%= form_for [@place, @post] do |f| %>
  <div class="field">
    <%= f.label :post_photo %>
    <%= f.file_field :post_photo %>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control'%>
  </div>

  <div class="field form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control'%>
  </div>

  <%= f.submit class: 'btn btn-default' %>

<% end %>

app/views/posts/_post.html.erb
<% if array.length > 0 %>
  <div class="row">
    <% array.each do |post| %>
      <div class="col-md-3">
        <div class="post-card">
          <a href="<%= place_post_path(post.place, post) %>"><%= image_tag post.post_photo.url(:medium), class: 'post-photo' %></a>
          <div class="post-profile">
            <%= image_tag post.post_user.profile_picture.url(:small), class: "img-circle"%>
          </div>
          <div class="post-info">
            <%= link_to post.post_user.full_name, user_path(post.post_user) %><br>
            <%= link_to post.place.name, place_path(post.place) %><br>
            <p><%= truncate(post.description, length: 26) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="message"><%= message %></p>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render partial: 'users/profile_heading', locals: {user: @post.post_user} %>

<div class="post-page">
  <% if current_user == @post.post_user %>
    <%= link_to "Edit Post", edit_place_post_path(@post.place), class: "btn btn-default" %>
    <%= link_to 'Delete Post', place_post_path(@post.place, @post),
                  data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-default" %>
  <% end %>

  <div class="post-card">
    <a href="<%= place_post_path(@post.place, @post) %>"><%= image_tag @post.post_photo.url(:medium), class: 'post-photo' %></a>
    <div class="post-profile">
      <%= image_tag @post.post_user.profile_picture.url(:small), class: "img-circle"%>
    </div>
    <div class="post-info">
      <%= link_to @post.post_user.full_name, user_path(@post.post_user) %><br>
      <%= link_to @post.place.name, place_path(@post.place) %><br>
      <p><%= @post.description %></p>
    </div>
  </div>
</div>