config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks", registrations: 'registrations' }
  root 'places#index'

  resources :entries do
    resources :comments
  end
  resources :users
  resources :places do
    resources :posts
  end

  get '/users/:id/follow_user', to: 'relationships#follow_user', as: :follow_user
  get '/users/:id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get '/users/:id/following', to: 'users#following', as: :following
  get '/users/:id/followers', to: 'users#followers', as: :followers
  get '/users/:id/journal', to: 'users#journal', as: :journal
  get '/search', to: 'search#search', as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :posts
  belongs_to :user

  scope :of_followed_users, -> (following_users) { where user_id: following_users }  

  # Finds place where search term matches name
  def self.search(search)
    where("name ILIKE ?", "%#{search}%") 
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :owned_place, only: [:edit, :update, :destroy]  

  # list all of a user's places
  def index
    if current_user && Place.of_followed_users(current_user.following).length > 0
      @places = Place.of_followed_users(current_user.following).order('created_at DESC')
    else
      @places = Place.all
    end
  end

  # show a specific place
  def show
  end

  # renders form to create new place
  def new
    @place = Place.new
  end

  # creates a new place
  def create
    @place = Place.new(user_id: current_user.id)
    @place.update(place_params)
    if @place.save
      redirect_to place_path(@place)
    else
      redirect_to controller: 'places', action: 'new'
    end
  end

  # renders form to edit place
  def edit
  end

  # updates place
  def update
    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      redirect_to controller: 'places', action: 'edit'
    end
  end

  # deletes a place
  def destroy
    @place.destroy
    redirect_to places_path
  end

  private
  # Finds the specific place
  def set_place
    @place = Place.find_by(id: params[:id])
  end

  # strong params for place
  def place_params
    params.require(:place).permit(:name)
  end

  # checks if a user owns a place to ensure that a user can't edit
  # other user's entries
  def owned_place  
    unless current_user == @place.user
      flash[:alert] = "That place doesn't belong to you!"
      redirect_to root_path
    end
  end  
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<!-- Partial displays the form for creating a new place or editing a place. Form styled with bootstrap. -->

<%= form_for(@place) do |f| %>
  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/places/edit.html.erb
<%= render partial: 'users/profile_heading', locals: {user: @place.user} %>

<h2 class="heading">Edit Place</h2>

<!-- Renders a form to edit a place -->
<%= render 'form' %>

app/views/places/index.html.erb
<%= render 'layouts/home_header' %>

<!-- Displays a list of places using bootstrap grid. -->

<h2 class="heading">Places</h2>

<% if @places.length > 0 %>
  <div class="row">
    <% @places.each do |place| %>
      <div class="col-sm-3">
        <div class="places">
          <%= link_to place.name, place_path(place), class: 'name-thumbnail place-name' %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="message">There are no places yet.</p>
<% end %>

app/views/places/new.html.erb
<!-- Renders form to create new place. -->
<%= render 'form' %>

app/views/places/show.html.erb
<%= render partial: 'users/profile_heading', locals: {user: @place.user} %>

<!-- Place show page displays all of the posts belonging to the place. -->
<h2 class="heading"><%= @place.name %></h2>

<% if current_user == @place.user %>
  <div class="links">
    <%= link_to "Create New Post", new_place_post_path(@place.id), class: 'btn btn-default' %>
    <%= link_to "Edit Place", edit_place_path, class: "btn btn-default" %>
    <%= link_to 'Delete Place', place_path(@place),
                  data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-default" %>
  </div>
<% end %>

<%= render partial: 'posts/post', locals: {array: @place.posts, message: "#{@place.name} doesn't have any posts yet."} %>