config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks", registrations: 'registrations' }
  root 'places#index'

  resources :entries do
    resources :comments
  end
  resources :users
  resources :places do
    resources :posts
  end

  get '/users/:id/follow_user', to: 'relationships#follow_user', as: :follow_user
  get '/users/:id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get '/users/:id/following', to: 'users#following', as: :following
  get '/users/:id/followers', to: 'users#followers', as: :followers
  get '/users/:id/journal', to: 'users#journal', as: :journal
  get '/search', to: 'search#search', as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Logo in the navbar links to the homepage -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li> <a href="/"><%= image_tag "Venture-logo.png", class: "logo" %></a> </li>
        </ul>
        
        <!-- Search bar in navigation -->
        <%= form_tag(search_path, :method => "get", id: "search-form", class: 'navbar-form navbar-left') do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: 'form-control' %>
              <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
            </div>
          <% end %>

        <!-- Navbar: if user is signed in then they see links to their profile and to sign out. If no user is signed in then they see links to sign in or sign up. -->
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_home_header.html.erb
<!-- Header for the home pages. Links to either a list of following users journal entries or following users places. -->
<div class="links">
  <%= link_to "Places", root_path, class: 'btn btn-default' %>
  <%= link_to "Journal Entries", entries_path, class: 'btn btn-default' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venture</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag :defaults %>
  </head>

  <body>

    <%= render 'layouts/header'%>

    <%= yield %>
  </body>
</html>